export const SET_PORTFOLIOS_ACTION = "SET_PORTFOLIOS_ACTION";
export const ADD_PORTFOLIOS_ACTION = "ADD_PORTFOLIOS_ACTION";
export const REMOVE_PORTFOLIO_ACTION = "REMOVE_PORTFOLIO_ACTION";
export const ADD_TRANSACTIONS_ACTION = "ADD_TRANSACTIONS_ACTION";
export const REMOVE_TRANSACTION_ACTION = "REMOVE_TRANSACTION_ACTION"
export const REMOVE_STOCK_ACTION = "REMOVE_STOCK_ACTION"